version: '3.8'

services:
  php-apache:
    build: .
    container_name: mi-php-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: mi-mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:

